services:

  # rename your service
  mysql_db:
    env_file: ./.env
    # update the version to your needs
    image: mariadb:10.5
    # rename your container
    container_name: container_name_mysql_db
    restart: unless-stopped 
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    # rename your volumes
    volumes:
      - name_db_volume:/var/lib/mysql
    networks:
      - development-network
    expose:
      - "3306"

  # rename your service
  apache2:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile.apache2php8.3
    # rename your image
    image: apache2-wordpress:1.0
    # rename your container 
    container_name: container_name_apache2
    restart: unless-stopped
    depends_on: 
    # rename your service
      - mysql_db
    volumes:
      - ./wp:/var/www/html
      - ./apache2.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      WP_SITEURL: ${WP_SITEURL}
      WP_CACHE: ${WP_CACHE}
      WP_DEBUG: ${WP_DEBUG}
      WP_DEBUG_LOG: ${WP_DEBUG_LOG}
      WP_DEBUG_DISPLAY: ${WP_DEBUG_DISPLAY}
      DISALLOW_FILE_MODS: ${DISALLOW_FILE_MODS}
      WP_AUTO_UPDATE_CORE: ${WP_AUTO_UPDATE_CORE}
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}
      WORDPRESS_DB_HOST: ${DATABASE_HOST}:${DATABASE_PORT}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
    networks:
      - development-network
    expose:
      - "80"

networks:
  development-network:
    external: true

volumes:
# rename your volumes 
  name_db_volume:
